### ISSUE TITLE
resolver fails in case of extra spaces in phantom.address

### ISSUE THREAD

**Issue by nnugumanov** [yandex/yandex-tank#155]
There was an extra space in phantom.address before closing bracket that broke the test:  [xxxx.xxx ]:443
Seems, it's a good idea to strip such spaces.

Tank log piece:

```
2015-06-11 15:03:10,603 [DEBUG] root Trying to resolve address string: [xxxx.xxx ]:443
2015-06-11 15:03:10,603 [DEBUG] root Braces and port present
2015-06-11 15:03:10,603 [DEBUG] root Match: xxxx.xxx  443 
2015-06-11 15:03:10,792 [DEBUG] tankcore Flushing config to: /var/lock/lunapark_0rbsCP.lock
2015-06-11 15:03:10,793 [ERROR] root Prepare error: Traceback (most recent call last):
  File "/usr/bin/tank_api_server.py", line 758, in prepare
    self.core.plugins_configure()
  File "/usr/lib/python2.7/dist-packages/tankcore.py", line 274, in plugins_configure
    plugin.configure()
  File "/usr/lib/yandex-tank/Tank/Plugins/Phantom.py", line 78, in configure
    self.phantom.read_config()
  File "/usr/lib/yandex-tank/Tank/Plugins/PhantomUtils.py", line 84, in read_config
    stream.read_config()
  File "/usr/lib/yandex-tank/Tank/Plugins/PhantomUtils.py", line 249, in read_config
    explicit_port)
  File "/usr/lib/yandex-tank/Tank/Plugins/PhantomUtils.py", line 363, in resolve
    resolved = self.lookup_fn(address_str, port)
gaierror: [Errno -2] Name or service not known

2015-06-11 15:03:10,793 [INFO] root Trying to clean up
```

**Comment by nettorta** [comment]
fixed
