### ISSUE TITLE
RuntimeError: Neither ammofile nor uris specified

### ISSUE THREAD

**Issue by weldpua2008** [yandex/yandex-tank#184]
Ubuntu 12.04 LTS:
When I tried to run it I got an error:

yandex-tank
```12:48:32 WARNING: /etc/yandex-tank is not acessible to get configs list
12:48:32 INFO: Loading configs...
12:48:32 INFO: Loading plugins...
12:48:32 INFO: Performing test
12:48:32 INFO: Configuring plugins...
12:48:32 INFO: Resolved 127.0.0.1 into 127.0.0.1:80
12:48:32 INFO: Configuring StepperWrapper...
12:48:32 WARNING: Graphite uploader is not configured and will not send any data
12:48:32 INFO: Preparing test...
12:48:32 INFO: Checking tank resources...
12:48:32 INFO: Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 263, in perform_test
    self.core.plugins_prepare_test()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 309, in plugins_prepare_test
    plugin.prepare_test()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 112, in prepare_test
    self.config = self.phantom.compose_config()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/PhantomUtils.py", line 92, in compose_config
    streams_config += stream.compose_config()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/PhantomUtils.py", line 263, in compose_config
    self.stepper_wrapper.prepare_stepper()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 193, in prepare_stepper
    self.stpd = self.__get_stpd_filename()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/stepper/main.py", line 245, in __get_stpd_filename
    "Neither ammofile nor uris specified")
RuntimeError: Neither ammofile nor uris specified

12:48:32 ERROR: Neither ammofile nor uris specified
12:48:32 INFO: Trying to shutdown gracefully...
12:48:32 INFO: Finishing test...
12:48:32 INFO: Finishing monitoring
12:48:33 INFO: Post-processing test...
12:48:33 WARNING: Loadosophia.org uploading disabled, please set loadosophia.token option to enable it, get token at https://loadosophia.org/service/upload/token/
12:48:33 INFO: Artifacts dir: logs/2015-12-03_12-48-33.aInrSN
12:48:33 INFO: Done graceful shutdown
12:48:33 INFO: Done performing test with code 1
```

The installation log:

```
# apt-get install python-pip build-essential libxml2-dev libxslt1-dev python-dev zlib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g-dev is already the newest version.
zlib1g-dev set to manually installed.
python-pip is already the newest version.
build-essential is already the newest version.
build-essential set to manually installed.
python-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  node-node-uuid libv8-3.7.12.22 libjpeg-progs libev4 libv8-dev libc6-dev:i386 libev-dev linux-libc-dev:i386 libc-ares-dev libjpeg-turbo-progs
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libxml2 libxml2:i386
Recommended packages:
  xml-core:i386
The following NEW packages will be installed:
  libxml2-dev libxslt1-dev
The following packages will be upgraded:
  libxml2 libxml2:i386
2 upgraded, 2 newly installed, 0 to remove and 403 not upgraded.
Need to get 2,705 kB of archives.
After this operation, 5,153 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://il.archive.ubuntu.com/ubuntu/ precise-updates/main libxml2 i386 2.7.8.dfsg-5.1ubuntu4.12 [662 kB]
Get:2 http://il.archive.ubuntu.com/ubuntu/ precise-updates/main libxml2 amd64 2.7.8.dfsg-5.1ubuntu4.12 [674 kB]
Get:3 http://il.archive.ubuntu.com/ubuntu/ precise-updates/main libxml2-dev amd64 2.7.8.dfsg-5.1ubuntu4.12 [805 kB]
Get:4 http://il.archive.ubuntu.com/ubuntu/ precise-updates/main libxslt1-dev amd64 1.1.26-8ubuntu1.3 [564 kB]
Fetched 2,705 kB in 2s (1,081 kB/s)
(Reading database ... 279351 files and directories currently installed.)
Preparing to replace libxml2:i386 2.7.8.dfsg-5.1ubuntu4.6 (using .../libxml2_2.7.8.dfsg-5.1ubuntu4.12_i386.deb) ...
De-configuring libxml2 ...
Unpacking replacement libxml2:i386 ...
pip install yandextankPreparing to replace libxml2 2.7.8.dfsg-5.1ubuntu4.6 (using .../libxml2_2.7.8.dfsg-5.1ubuntu4.12_amd64.deb) ...
Unpacking replacement libxml2 ...
Setting up libxml2:i386 (2.7.8.dfsg-5.1ubuntu4.12) ...
Setting up libxml2 (2.7.8.dfsg-5.1ubuntu4.12) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place

Selecting previously unselected package libxml2-dev.
(Reading database ... 279351 files and directories currently installed.)
Unpacking libxml2-dev (from .../libxml2-dev_2.7.8.dfsg-5.1ubuntu4.12_amd64.deb) ...
Selecting previously unselected package libxslt1-dev.
Unpacking libxslt1-dev (from .../libxslt1-dev_1.1.26-8ubuntu1.3_amd64.deb) ...
Processing triggers for man-db ...
Setting up libxml2-dev (2.7.8.dfsg-5.1ubuntu4.12) ...
Setting up libxslt1-dev (1.1.26-8ubuntu1.3) ...
root@RDE-1.3:/home.local/valerys/rde_devops_tools/dfcc/etcd/jmeter# pip install yandextank
/usr/local/lib/python2.7/dist-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting yandextank
/usr/local/lib/python2.7/dist-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading yandextank-1.7.19-py2-none-any.whl (138kB)
    100% |████████████████████████████████| 139kB 916kB/s
Requirement already satisfied (use --upgrade to upgrade): psutil>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from yandextank)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages (from yandextank)
Collecting progressbar (from yandextank)
  Downloading progressbar-2.3.tar.gz
Collecting ipaddr (from yandextank)
  Downloading ipaddr-2.1.11.tar.gz
Installing collected packages: progressbar, ipaddr, yandextank
  Running setup.py install for progressbar
  Running setup.py install for ipaddr
Successfully installed ipaddr-2.1.11 progressbar-2.3 yandextank-1.7.19

```

**Comment by nnugumanov** [comment]
Show please command line and load.ini. It seems that you've missed ammo or uri file in command line / config file.
