### ISSUE TITLE
NoValidConnectionsError: [Errno None] Unable to connect to port 22 on  or [my_target_ip]

### ISSUE THREAD

**Issue by ulrith** [yandex/yandex-tank#203]
I've installed yandex-tank and phantom on the remote machine with aim to test some other server. When I start test I've get the following error

```
yandex-tank
13:09:13 WARNING: /etc/yandex-tank is not acessible to get configs list
13:09:13 INFO: No config passed via cmdline, using ./load.ini
13:09:13 INFO: Loading configs...
13:09:13 INFO: Loading plugins...
13:09:13 INFO: Performing test
13:09:13 INFO: Configuring plugins...
13:09:13 WARNING: Using phantom.port option is deprecated. Use phantom.address=[address]:port instead
13:09:13 INFO: Resolved [my_target_ip] into [my_target_ip]:80
13:09:13 INFO: Configuring StepperWrapper...
13:09:13 WARNING: Graphite uploader is not configured and will not send any data
13:09:13 INFO: Preparing test...
13:09:13 INFO: Checking tank resources...
13:09:13 INFO: Using cached stpd-file: logs/_1ffa66470d0fd10e018a586f5aa84783.stpd
13:09:13 INFO: rps_schedule is set. Overriding cached instances param from config: 1000
13:09:13 INFO: Starting monitoring with config: /home/solaradmin/logs/monitoring_default_tx8WgD.xml
13:09:13 INFO: Installing monitoring agent at solaradmin@[my_target_ip]...
13:09:13 INFO: Creating temp dir on [my_target_ip]
13:09:13 INFO: Execute on [my_target_ip]: /usr/bin/env python2 -c "import tempfile; print tempfile.mkdtemp();"
13:09:13 ERROR: Failed to install monitoring agent to [my_target_ip]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Monitoring/collector.py", line 255, in install
    out, errors, err_code = self.ssh.execute(cmd)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Monitoring/collector.py", line 96, in execute
    with self.connect() as client:
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Monitoring/collector.py", line 66, in connect
    timeout=self.timeout,
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 311, in connect
    raise NoValidConnectionsError(errors)
**NoValidConnectionsError: [Errno None] Unable to connect to port 22 on  or [my_target_ip]**
13:09:14 ERROR: Could not start monitoring

```
I don't understand why yandex-tank tries to connect to ssh port on my target machine?
Probably I have wrong understanding of what 'target' means in terms of phantom config? Here it is:

```
[phantom]
address=[my_target_ip] ;Target's address
port=80 ;target's port
rps_schedule=line(1, 100, 1m) ;load scheme
ssl=1
; Headers and URIs for GET requests
header_http = 1.1
headers = [Host: [my_target_domain]]
  [Connection: close]
uris = /
```

**Comment by direvius** [comment]
Yandex.Tank installs a monitoring agent to the target machine by default to collect monitoring metrics. 
```
13:09:13 ERROR: Failed to install monitoring agent to [my_target_ip]
```
You can disable this behavior explicitly in your config.

**Comment by AlexandrBoltris** [comment]
I have the same errors while starting the Yandex.Tank, but my question is: **how to change the ssh port**.

This comment may be useful if your ssh server is running on a non-standard port (not 22).

By default Yandex.Tank uses Telegraf for host monitoring.

To change the ssh port for Telegraf you will need to specify config file for Telegraf. Simply add a new section into your **load.ini** file:

```
[telegraf]
config=monitoring.xml
```

Here is **monitoring.xml** file:
```
<Monitoring>
        <Host address="[target]" port="XXXX" />
</Monitoring>
```

NOTE: replace **XXXX** with the actual ssh port on your server.
