### ISSUE TITLE
Can't run yandex-tank on Mac OSX

### ISSUE THREAD

**Issue by Abdujabbor** [yandex/yandex-tank#401]
Hi! Can anybody help with this problem? I have searched but not found the solution.
```
docker run -v $(pwd):/var/loadtest -v $HOME/.ssh:/root/.ssh --net host -it direvius/yandex-tank
Unable to find image 'direvius/yandex-tank:latest' locally
latest: Pulling from direvius/yandex-tank
b6f892c0043b: Pull complete 
55010f332b04: Pull complete 
2955fb827c94: Pull complete 
3deef3fcbd30: Pull complete 
cf9722e506aa: Pull complete 
0f21e3d49076: Pull complete 
55f76d1544b0: Pull complete 
5afa7371aca9: Pull complete 
3ab9434cdd20: Pull complete 
Digest: sha256:ea594260b543281a4a1163757b0428a9723d36f567820dc87959ee4586c7be81
Status: Downloaded newer image for direvius/yandex-tank:latest
07:15:03 [WARNING] /etc/yandex-tank is not accessible to get configs list
07:15:03 [INFO] Loading configs...
07:15:03 [INFO] Loading plugins...
07:15:03 [INFO] Performing test
07:15:03 [INFO] Configuring plugins...
07:15:03 [WARNING] Failed TCP connection test using [127.0.0.1]:80
07:15:03 [WARNING] Failed TCP connection test using [127.0.0.1]:80
07:15:03 [WARNING] Failed TCP connection test using [127.0.0.1]:80
07:15:03 [INFO] Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 267, in perform_test
    self.core.plugins_configure()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 263, in plugins_configure
    plugin.configure()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 93, in configure
    self.phantom.read_config()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 101, in read_config
    stream.read_config()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 575, in resolve
    raise RuntimeError(msg % address_str)
RuntimeError: All connection attempts failed for 127.0.0.1, use phantom.connection_test=0 to disable it

07:15:03 [ERROR] All connection attempts failed for 127.0.0.1, use phantom.connection_test=0 to disable it
07:15:03 [INFO] Trying to shutdown gracefully...
07:15:03 [INFO] Finishing test...
07:15:03 [INFO] Finishing monitoring
07:15:03 [ERROR] Failed finishing plugin <yandextank.plugins.Aggregator.plugin.Plugin object at 0x7f2cd7908090>: 'Plugin' object has no attribute 'drain'
07:15:03 [INFO] Post-processing test...
07:15:03 [ERROR] Failed post-processing plugin <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f2cd7908790>: 'Plugin' object has no attribute 'data_and_stats_stream'
07:15:03 [INFO] Artifacts dir: /var/loadtest/logs/2017-08-15_07-15-03.DTcbK4
07:15:03 [INFO] Done graceful shutdown
07:15:03 [INFO] Close allocated resources...
07:15:03 [INFO] Done performing test with code 1
```

**Comment by nettorta** [comment]
Hi,
You are trying to load test the localhost - [127.0.0.1]:80
Before sending requests, tank tries to detect whether 'target' alive or not (just opens a TCP-connection to specified address and port).

Most likely, you want to load test another host and not configured YTank properly. 

RTD tutorial for Y.Tank configuration:
http://yandextank.readthedocs.io/en/latest/tutorial.html

**Comment by Abdujabbor** [comment]
@nettorta  Thank you ! ! ! thanks for quickly answer ! ! !
