### ISSUE TITLE
Cant run Yandex-tank after installation via PyPi Ubuntu 16.04

### ISSUE THREAD

**Issue by 0xc00000f** [yandex/yandex-tank#538]
Python 3.5.2; PyPi 9.0.1; xubuntu 16.04

khomyak@khomyak-VirtualBox:~/workspace/uir$ yandex-tank -c load.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/yandex-tank", line 11, in <module>
    load_entry_point('yandextank==1.9.10', 'console_scripts', 'yandex-tank')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/yandextank/core/__init__.py", line 4, in <module>
    from .tankcore import TankCore  # noqa:F401
  File "/usr/local/lib/python3.5/dist-packages/yandextank/core/tankcore.py", line 33, in <module>
    from ..plugins.Telegraf import Plugin as TelegrafPlugin
  File "/usr/local/lib/python3.5/dist-packages/yandextank/plugins/Telegraf/__init__.py", line 1, in <module>
    from .plugin import *  # noqa:F401,F403
  File "/usr/local/lib/python3.5/dist-packages/yandextank/plugins/Telegraf/plugin.py", line 20, in <module>
    from ..Autostop import Plugin as AutostopPlugin, AbstractCriterion
  File "/usr/local/lib/python3.5/dist-packages/yandextank/plugins/Autostop/__init__.py", line 1, in <module>
    from .plugin import Plugin  # noqa:F401
  File "/usr/local/lib/python3.5/dist-packages/yandextank/plugins/Autostop/plugin.py", line 8, in <module>
    from ..Console import Plugin as ConsolePlugin
  File "/usr/local/lib/python3.5/dist-packages/yandextank/plugins/Console/__init__.py", line 1, in <module>
    from .plugin import *  # noqa:F401,F403
  File "/usr/local/lib/python3.5/dist-packages/yandextank/plugins/Console/plugin.py", line 7, in <module>
    from .screen import Screen
  File "/usr/local/lib/python3.5/dist-packages/yandextank/plugins/Console/screen.py", line 1021
    key=lambda (k, v): (-1 * v[self.cases_sort_by], k))
               ^
SyntaxError: invalid syntax

**Comment by 0xc00000f** [comment]
Problem is solved with installing using Python2.7
