### ISSUE TITLE
Can not work on python 3.5 version

### ISSUE THREAD

**Issue by jualy007** [yandex/yandex-tank#624]
After successful install yandex-tank, I am try to get help info, but get errors:
Traceback (most recent call last):
  File "/opt/Python-3.5.5/bin/yandex-tank", line 7, in <module>
    from yandextank.core.cli import main
  File "/opt/Python-3.5.5/lib/python3.5/site-packages/yandextank/core/cli.py", line 6, in <module>
    from yandextank.core.consoleworker import ConsoleTank, CompletionHelperOptionParser
  File "/opt/Python-3.5.5/lib/python3.5/site-packages/yandextank/core/consoleworker.py", line 2, in <module>
    from ConfigParser import ConfigParser, MissingSectionHeaderError, NoOptionError, NoSectionError
ImportError: No module named 'ConfigParser'

ConfigParser is python2 module, and python3 have rename to configparser

**Comment by anton-tagunov** [comment]
up

Guys are you plaining to add support python3 ? Currently setup.py says that python3 is supported, but it didn't actualy.

**Comment by direvius** [comment]
did not plan that for nearest releases. Will remove from setup.py.
