### ISSUE TITLE
Data uploader error

### ISSUE THREAD

**Issue by AlexeyProskuryakov** [yandex/yandex-tank#703]
Здравствуйте! Проблема с отправкой данных в overload видимо (но это не точно). 
Конфигурация такова:
```
phantom:
  address: xxxxx:8000 
  header_http: "1.1"
  headers:
    - "[Host: www.target.example.com]"
    - "[Connection: close]"
  uris:
    - /xxxxx/yyy/zzz
    - /xxxxx/xxxx/
    - /xxxxx/xx/
  load_profile:
    load_type: rps # schedule load by defining requests per second
    schedule: line(1, 10, 5m) # starting from 1rps growing linearly to 10rps during 10 minutes
  ammo_type: uripost

console:
  enabled: true # enable console output

telegraf:
  enabled: false # let's disable telegraf monitoring for the first time

overload:
  enabled: true
  package: yandextank.plugins.DataUploader
  token_file: "token.txt"

autostop:
  autostop:
    - time(1s,10s)
    - http(5xx,100%,1s)
    - net(xx,1,30)

```
Получаю следующую проблему: 
```
2019-01-24 05:18:51,793	Failed post-processing plugin <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7fb155480c90>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 313, in plugins_post_process
    retcode = plugin.post_process(retcode)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/DataUploader/plugin.py", line 316, in post_process
    self.events.join()
  File "/usr/lib/python2.7/threading.py", line 929, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
```

**Comment by fomars** [comment]
Ошибка, которую вы приводите, скорее всего вторична, в логе должна быть какая-то ошибка до этого. Если не найдете, пришлите весь лог tank.log

**Comment by AlexeyProskuryakov** [comment]
Извиняюсь, контекст ушел.
