### ISSUE TITLE
No handlers could be found for logger "netort.resource"

### ISSUE THREAD

**Issue by mkoshevoi** [yandex/yandex-tank#796]
alias yandex-tank-docker='docker run -v /root/config:/var/loadtest -v /root/.ssh:/root.ssh -it direvius/yandex-tank'

yandex-tank-docker -c load.yaml
No handlers could be found for logger "netort.resource"
Traceback (most recent call last):
  File "/usr/local/bin/yandex-tank", line 11, in <module>
    load_entry_point('yandextank==1.12.1', 'console_scripts', 'yandex-tank')()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/cli.py", line 111, in main
    handlers = init_logging(options.error_log, options.verbose, options.quiet)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/cli.py", line 191, in init_logging
    err_file_handler = logging.FileHandler(events_log_fname)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/loadtest/tank_errors.log'

**Comment by mkoshevoi** [comment]
Linux instance-template-1 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mkoshevoi** [comment]
[tank]root@9e47adbf366d: /var/loadtest # ls -lah
ls: cannot open directory '.': Permission denied

**Comment by mkoshevoi** [comment]
selinux
