### ISSUE TITLE
Build fresh docker image

### ISSUE THREAD

**Issue by sashayakovtseva** [yandex/yandex-tank#860]
Hello,

The most recent image at https://hub.docker.com/r/direvius/yandex-tank is two years old.
Could you update them with the latest Tank version please.

I've tries to build new image myself, but get this error:
```
#6 20.53 Reading state information...
#6 20.54 E: Unable to locate package phantom
#6 20.54 E: Unable to locate package phantom-ssl
------
executor failed running [/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&     apt-get update -q &&     apt-get install --no-install-recommends -yq         sudo             vim              wget             curl             less             iproute2         software-properties-common         telnet           atop             openssh-client         git                    python3-pip  &&     add-apt-repository ppa:yandex-load/main -y &&     apt-get update -q &&     apt-get install -yq         phantom         phantom-ssl &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /var/tmp/*]: exit code: 100
```

**Comment by kamartem** [comment]
What cpu arch? M1?

**Comment by des1roer** [comment]
Dockerfile

    FROM ubuntu:focal

    ARG BRANCH=master

    RUN export DEBIAN_FRONTEND=noninteractive && \
        apt-get update -q && \
        apt-get install --no-install-recommends -yq \
            sudo     \
            vim      \
            wget     \
            curl     \
            less     \
            iproute2 \
            software-properties-common \
            telnet   \
            atop     \
            openssh-client \
            git            \
            gpg-agent      \
            python3-pip  && \
        add-apt-repository ppa:yandex-load/main -y && \
        apt-get update -q && \
        apt-get install -yq \
            phantom \
            phantom-ssl && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /var/tmp/*

    ENV BUILD_DEPS="python3-dev build-essential gfortran libssl-dev libffi-dev"
    RUN export DEBIAN_FRONTEND=noninteractive && \
        apt-get update && \
        apt-get install -yq --no-install-recommends ${BUILD_DEPS} && \
        pip3 install --upgrade setuptools && \
        pip3 install --upgrade pip && \
        pip3 install https://api.github.com/repos/yandex/yandex-tank/tarball/${BRANCH} && \
        apt-get autoremove -y ${BUILD_DEPS} && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /var/tmp/* /root/.cache/* \

    #RUN apt-get update && apt-get install -y python3-pip build-essential python3-dev libffi-dev gfortran libssl-dev
    #
    #RUN pip3 install --no-cache-dir --upgrade pip --upgrade setuptools
    #
    #RUN pip3 install https://api.github.com/repos/yandex/yandex-tank/tarball/master

    #RUN apt-get install -y software-properties-common
    #RUN add-apt-repository ppa:yandex-load/main
    #RUN apt-get install phantom phantom-ssl

    ENTRYPOINT ["yandex-tank"]

при установке

    #0 53.53 Collecting typing
    #0 53.57   Downloading typing-3.7.4.3.tar.gz (78 kB)
    #0 54.96 Collecting grpcio>=1.44.0
    #0 54.97   Using cached grpcio-1.54.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
    #0 56.28 Collecting grpcio-tools
    #0 56.29   Using cached grpcio_tools-1.54.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
    #0 56.45 Collecting PyJWT
    #0 56.49   Downloading PyJWT-2.7.0-py3-none-any.whl (22 kB)
    #0 56.52 Processing /tmp/pip-req-build-93o5zww4/netort
    #0 56.65     ERROR: Command errored out with exit status 1:
    #0 56.65      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0y5pi0zo/netort/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0y5pi0zo/netort/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0y5pi0zo/netort/pip-egg-info
    #0 56.65          cwd: /tmp/pip-install-0y5pi0zo/netort/
    #0 56.65     Complete output (5 lines):
    #0 56.65     Traceback (most recent call last):
    #0 56.65       File "<string>", line 1, in <module>
    #0 56.65       File "/usr/lib/python3.8/tokenize.py", line 392, in open
    #0 56.65         buffer = _builtin_open(filename, 'rb')
    #0 56.65     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-0y5pi0zo/netort/setup.py'
    #0 56.65     ----------------------------------------
    #0 56.81 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ------
    failed to solve: executor failed running [/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&     apt-get update &&     apt-get install -yq --no-install-recommends ${BUILD_DEPS} &&     pip3 install --upgrade setuptools &&     pip3 install --upgrade pip &&     pip3 install https://api.github.com/repos/yandex/yandex-tank/tarball/${BRANCH} &&     apt-get autoremove -y ${BUILD_DEPS} &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /var/tmp/* /root/.cache/* ENTRYPOINT ["yandex-tank"]]: exit code: 1
    ➜

**Comment by griddic** [comment]
> The most recent image at https://hub.docker.com/r/direvius/yandex-tank is two years old.

The official images are located here: https://hub.docker.com/r/yandex/yandex-tank


> I've tries to build new image myself, but get this error:

Please try again.
I've just tested it with docker-compose: https://github.com/griddic/code_blocks/tree/master/history/2023/tank_telegraf_compose
